import { useEffect, useState } from 'react'
import './App.css'

type Run = {id:string; name:string; start:string; end:string; bars:number; final_equity:number; return_pct:number; max_drawdown_pct:number; fees:number; completed_trades:number; win_rate_pct:number|null; curve:{date:string;equity:number}[]; trades:{date:string;side:string;price:number;quantity:number;fee:number}[]}
const num=(n:number)=>n.toLocaleString('fr-FR',{maximumFractionDigits:2})
const tabs=['Vue d’ensemble','Backtesting','Stratégie','Portefeuille','Assistant IA']
export default function App(){
 const [tab,setTab]=useState(tabs[0]),[runs,setRuns]=useState<Run[]>([]),[selected,setSelected]=useState<Run|null>(null)
 const [csv,setCsv]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[online,setOnline]=useState(false)
 const [capital,setCapital]=useState(10000),[fast,setFast]=useState(20),[slow,setSlow]=useState(50),[fee,setFee]=useState(10),[slip,setSlip]=useState(5),[allocation,setAllocation]=useState(20)
 useEffect(()=>{fetch('/api/health').then(r=>setOnline(r.ok)).catch(()=>setOnline(false));fetch('/api/backtests').then(r=>{if(!r.ok)throw Error();return r.json()}).then((data:Run[])=>{setRuns(data);setSelected(data[0]??null)}).catch(()=>setError('API indisponible. Démarrez le backend puis rechargez la page.'))},[])
 async function loadFile(file?:File){if(!file)return;setError('');if(file.size>2_000_000){setError('Le fichier doit faire moins de 2 Mo.');return}setCsv(await file.text());setName(file.name.replace(/\.csv$/i,''))}
 async function launch(){setBusy(true);setError('');try{const response=await fetch('/api/backtests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csv,name,capital,fast,slow,fee_bps:fee,slippage_bps:slip,allocation:allocation/100})});const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:'Vérifiez les paramètres et le format CSV.');setSelected(data);setRuns(prev=>[data,...prev].slice(0,30));setTab(tabs[0])}catch(e){setError(e instanceof Error?e.message:'Échec du backtest.')}finally{setBusy(false)}}
 async function demo(){const text=await fetch('/demo-synthetique.csv').then(r=>r.text());setCsv(text);setName('DÉMO · données synthétiques');setTab('Backtesting')}
 const run=selected
 const values=run?.curve.map(p=>p.equity)??[];const lo=Math.min(...values),hi=Math.max(...values)
 const points=values.map((v,i)=>`${i/Math.max(1,values.length-1)*900},${190-(v-lo)/(hi-lo||1)*160}`).join(' ')
 return <div className="shell"><aside><div className="brand"><span className="brandmark">↗</span> trading<span>ai</span></div><div className="workspace">ESPACE DE RECHERCHE</div><nav>{tabs.map((t,i)=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}><span>{['◫','↗','≋','▣','✧'][i]}</span>{t}</button>)}</nav><div className="sidefoot"><span className="dot"/> Simulation uniquement<p>Votre laboratoire quantitatif.<br/>Aucun ordre réel.</p><small>VERSION 0.1</small></div></aside><main><header><span>Workspace / <b>{tab}</b></span><span className="status"><i className={online?'dot':'dot off'}/>{online?'API connectée':'API hors ligne'}</span></header><div className="content"><div className="heading"><div><div className="eyebrow">TRADING AI · RESEARCH LAB</div><h1>{tab==='Vue d’ensemble'?'De l’idée à la preuve.':tab}</h1><p>Explorez une stratégie. Mesurez ses résultats. Comprenez le risque.</p></div><span className="pill">MODE SIMULATION</span></div>{error&&<div role="alert" className="error">{error}</div>}
 {(tab==='Vue d’ensemble'||tab==='Backtesting')&&<>
 <section className="metrics">{[['Capital final',run?num(run.final_equity):'—','Devise du CSV'],['Performance nette',run?num(run.return_pct)+' %':'—','Après frais et glissement'],['Drawdown maximal',run?num(run.max_drawdown_pct)+' %':'—','Baisse depuis le plus haut'],['Allers-retours',run?String(run.completed_trades):'—','Positions clôturées']].map(([label,value,hint])=><article key={label}><label>{label}</label><strong>{value}</strong><small>{hint}</small></article>)}</section>
 {tab==='Backtesting'?<section className="panel"><div className="panelhead"><h2>Configurer une expérience</h2><span>EMA · Long uniquement</span></div><p>Importez un historique quotidien CSV : <code>date,open,close</code>. Dates ISO, prix positifs et dates croissantes.</p><label className="upload">↑ Choisir un fichier CSV<input aria-label="Historique CSV" type="file" accept=".csv,text/csv" onChange={e=>void loadFile(e.target.files?.[0])}/></label><div className="form"><label>Nom de l’expérience<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label>{[['Capital initial',capital,setCapital],['EMA rapide',fast,setFast],['EMA lente',slow,setSlow],['Frais (points de base)',fee,setFee],['Glissement (points de base)',slip,setSlip],['Allocation maximale (%)',allocation,setAllocation]].map(([label,value,setter])=><label key={String(label)}>{String(label)}<input type="number" value={Number(value)} onChange={e=>(setter as (n:number)=>void)(Number(e.target.value))}/></label>)}</div><div className="actions"><button className="primary" disabled={busy||!csv||!name.trim()} onClick={()=>void launch()}>{busy?'Calcul en cours…':'Lancer le backtest →'}</button><button onClick={()=>void demo()}>Charger la démo synthétique</button></div><small>20 % du capital par position par défaut · 10 points de base = 0,10 %.</small></section>:<section className="panel"><div className="panelhead"><h2>Évolution du capital</h2><span>{run?run.name:'Votre première expérience'}</span></div>{run?<><svg className="chart" viewBox="0 0 900 220" role="img" aria-label="Courbe de capital du backtest"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#51d6b0" stopOpacity=".25"/><stop offset="100%" stopColor="#51d6b0" stopOpacity="0"/></linearGradient></defs>{[30,85,140,195].map(y=><line key={y} x1="0" x2="900" y1={y} y2={y} stroke="#26343b"/>)}<polygon points={`0,220 ${points} 900,220`} fill="url(#area)"/><polyline points={points} fill="none" stroke="#57d9b3" strokeWidth="3"/></svg><div className="chartcaption"><span>{run.start} → {run.end} · {run.bars} séances</span><span>Min. {num(lo)} / Max. {num(hi)}</span></div></>:<div className="empty"><div className="emptyicon">⌁</div><h2>Chaque stratégie commence par un test.</h2><p>Importez vos données historiques pour obtenir votre première courbe.</p><button className="primary" onClick={()=>setTab('Backtesting')}>Créer un backtest →</button><button className="textbutton" onClick={()=>void demo()}>Essayer avec des données synthétiques</button></div>}</section>}
 <div className="bottomgrid"><section className="panel"><div className="panelhead"><h2>Expériences récentes</h2><span>{runs.length} résultats</span></div>{runs.length?runs.map(r=><button className={'history '+(run?.id===r.id?'chosen':'')} key={r.id} onClick={()=>{setSelected(r);setTab(tabs[0])}}><span>{r.name}<small>{r.start} → {r.end}</small></span><b>{num(r.return_pct)} % ↗</b></button>):<p>Aucun résultat enregistré pour le moment.</p>}</section><section className="panel"><span className="eyebrow">UNE MÉTHODE TRANSPARENTE</span><h2>Les règles avant l’intuition.</h2><p>EMA rapide au-dessus de l’EMA lente : achat à l’ouverture suivante. Sortie lorsque la condition s’inverse.</p><p>Frais, glissement et liquidation finale inclus. Aucun effet de levier.</p><button onClick={()=>setTab('Stratégie')}>Voir les hypothèses →</button></section></div>
 {run&&<section className="panel"><div className="panelhead"><h2>Journal des transactions</h2><span>Frais : {num(run.fees)} · Réussite : {run.win_rate_pct===null?'—':num(run.win_rate_pct)+' %'}</span></div><div className="tablewrap"><table><thead><tr>{['Date','Opération','Prix exécuté','Quantité','Frais'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{run.trades.map((t,i)=><tr key={i}><td>{t.date}</td><td>{t.side}</td><td>{num(t.price)}</td><td>{num(t.quantity)}</td><td>{num(t.fee)}</td></tr>)}</tbody></table>{!run.trades.length&&<p>Aucun signal sur cette période.</p>}</div></section>}
 </>}
 {tab==='Stratégie'&&<section className="panel prose"><h2>Croisement de deux moyennes exponentielles</h2><p>Les EMA sont initialisées au premier cours de clôture. Le moteur attend la période lente avant de prendre une position. Les signaux utilisent uniquement les clôtures déjà connues ; les ordres s’exécutent à l’ouverture suivante.</p><h3>Hypothèses de simulation</h3><p>Une seule position longue, fractions de titres autorisées, allocation calculée à chaque entrée, aucun emprunt. Frais proportionnels à chaque ordre ; glissement défavorable à l’achat et à la vente. La dernière position est liquidée à la dernière clôture.</p><p>Le CSV doit contenir des séances quotidiennes, une seule devise et des cours open/close ajustés de façon cohérente. Les dividendes ne sont pas crédités séparément. Le résultat dépend de la qualité de vos données.</p><h3>À construire ensuite</h3><p>Comparaison achat-conservation, séparation apprentissage/évaluation, RSI, limites de pertes et paper trading. Aucun score IA ni promesse de performance dans cette version.</p></section>}
 {(tab==='Portefeuille'||tab==='Assistant IA')&&<section className="panel empty"><div className="emptyicon">{tab==='Portefeuille'?'▣':'✧'}</div><h2>{tab==='Portefeuille'?'Le portefeuille viendra avec le paper trading.':'L’assistant IA est prévu pour la prochaine étape.'}</h2><p>{tab==='Portefeuille'?'La V1 conserve les résultats de backtests. Aucun compte de courtier n’est connecté.':'Nous validons d’abord les données et les calculs. Aucun modèle IA n’est connecté.'}</p><button onClick={()=>setTab('Backtesting')}>Ouvrir le laboratoire →</button></section>}
 <footer>TRADING AI <span>Recherche & simulation · Les résultats historiques ne préjugent pas des résultats futurs.</span></footer></div></main></div>
}
